esphome:
  name: espair
  platform: ESP32
  board: esp32doit-devkit-v1
  includes:
    - sm300d2.h

uart:
  id: uart_bus
  data_bits: 8
  stop_bits: 1
  tx_pin: GPIO5
  rx_pin: GPIO4
  baud_rate: 9600

text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP Address
      id: ip
    ssid:
      name: Connected SSID
      id: ssid
    
sensor:
  - platform: wifi_signal
    name: "WiFi Signal ${upper_devicename}"
    update_interval: 60s
  - platform: uptime
    name: Uptime
  - platform: custom
    lambda: |-
      auto espair_sensor = new SM300D2Sensor(id(uart_bus));
      App.register_component(espair_sensor);
      return {
        espair_sensor->co2_sensor, 
        espair_sensor->formaldehyde_sensor, 
        espair_sensor->tvoc_sensor,
        espair_sensor->pm2_5_sensor,
        espair_sensor->pm10_sensor,
        espair_sensor->temperature_sensor,
        espair_sensor->humidity_sensor
      };
    sensors:
      - name: "CO₂"
        unit_of_measurement: "ppm"
        accuracy_decimals: 0
        icon: "mdi:molecule-co2"
        expire_after: 60s

      - name: "Formaldehyde"
        unit_of_measurement: "µg/m³"
        accuracy_decimals: 0
        icon: "mdi:flask"
        expire_after: 60s

      - name: "TVOC"
        unit_of_measurement: "µg/m³"
        accuracy_decimals: 0
        icon: "mdi:chemical-weapon"
        expire_after: 60s

      - name: "PM2.5"
        unit_of_measurement: "µg/m³"
        accuracy_decimals: 0
        icon: "mdi:grain"
        expire_after: 60s

      - name: "PM10"
        unit_of_measurement: "µg/m³"
        accuracy_decimals: 0
        icon: "mdi:grain"
        expire_after: 60s

      - name: "Temperature"
        unit_of_measurement: "°C"
        accuracy_decimals: 1
        icon: "mdi:thermometer"
        expire_after: 60s

      - name: "Humidity"
        unit_of_measurement: "%"
        accuracy_decimals: 1
        icon: "mdi:water-percent"
        expire_after: 60s